account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (PwdResetConfirmForm, PwdResetForm, UserLoginForm)



app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='account/password_reset/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset/password_reset_confirm.html',
                                                                                                success_url='/account/password_reset_complete/', 
                                                                                                form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_complete'),
    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/dashboard/delete_confirm.html"), name='delete_confirmation'),
    path('profile/', views.profile, name='users-profile'),
    path('orders/', views.user_orders, name= 'user_orders'),
    # user Address
    path("addresses/", views.view_address, name="addresses"),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),
     # Wish List
    path("wishlist", views.wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist"),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='homepage'),
    path('search/', views.post_search, name='post_search'),
    path('all_blog/', views.all_blog, name='all_blog'),
    path('addcomment/', views.addcomment, name='addcomment'),
    path('<slug:post>/', views.post_single, name='post_single'),
    path('category/<category>/', views.CatListView.as_view(),name="category"),
]

sellbook/urls.py
from django.urls import path

from . import views

app_name = 'sellbook'

urlpatterns = [
    path('', views.home, name='homepage'),
    path('sellbook/<slug:category_slug>/', views.category_list, name='category_list'),
    path('sellbook/<slug:slug>', views.product_detail, name='product_detail'),
    path('sellbook1/<slug:slug>', views.product_detail1, name='product_detail1'),
    path('mybooks/', views.mybooks, name='mybooks'),
    path('mybooks/edit/<int:pk>', views.edit_books, name='edit_books'),
    path('mybooks/delete/<int:pk>', views.delete_books, name='delete_books'),
    path('mybooks/sold_books/', views.mysoldbooks, name='mysoldbooks'),
]

templates/oldbooks/category.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block content%}
<head>
  <link rel="stylesheet"  href="{% static '/css/product_page2.css' %}">
</head>

<div id = "wrapper">
    
    <div id="filter">
      <div >
        <div class="a" style="font-size: 16px" id="filter_head">
          <strong>FILTERS</strong>
        </div>
        
        <div class="box">
  
          <label class="container"
              ><strong><div class="pb-3 h5">{{category.name|title}}</div></strong></label>
  
    
          </div>
    
          <div class="box">
            <p><strong>CATEGORIES</strong></p>
    
            {% for c in categoriess %}
  
  
            <label class="container" {% if categoriess.slug == c.slug %}class="selected" {% endif %}
              ><a class="" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
              <span></span></label
            >
            {% endfor %}
    
    
          </div>
    
    
  
        </div> 
        
      </div>


      <div class = "products" id = "container">
        {% if products|length == 0 %}

        <h3>  oopsss !!! There are no Products</h3>
        {% endif %}

        {% for product in products %} 
        
        <div class = 'conatiner' style ="cursor: pointer;"   >

          <a href="{{ product.get_absolute_url }}"><img class= 'img-fluid' src="{{ product.image1.url }}" alt="{{ image.image.alt_text }}" ></a>

        <div class = "contentBox">
        
        
        <h4>{{ product.selling_prod.product.title }}</h4>
        <div class = "mixbox">
          
        <p>₹{{ product.discount_price}}</p>
        <p>{{ product.tag }}</p>
          <p class = "strikep">₹{{product.regular_price}}</p>
          <p class = "offerp">({{product.discount_percentage}}% OFF)</p>
              
    
            </div>
            <p>{{ product.selling_user.user.name }}</p>


            </div>
                  
        </div> 
        {% endfor %}  
      </div>  
    
        
        
        
        
        
        
    
      </div>
      <div class="py-4">
        <nav aria-label="Page navigation example">
          {% if products.has_other_pages %}
          <ul class="pagination">
            {% if product.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
            {% endif %}
            {% for num in products.paginator.page_range %}
            {% if products.number == l %}
            <li class="page-item active"><span class="page-link">{{ num }} <span class="sr-only">(current)</span></span>
            </li>
            {% else %}
            <li><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
            {% endfor %}
            {% if products.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">Next</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
            {% endif %}
          </ul>
          {% endif %}
        </nav>
      </div>
</div>

<style>
  .box {
    background-color: #f9f9f9;
    padding: 20px;
    border-radius: 10px;
    margin-bottom: 20px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  }
  
  /* Container styles */
  .container {
    display: block;
    margin-bottom: 10px;
  }
  
  /* Checkbox styles */
  .container input[type="checkbox"] {
    margin-right: 10px;
  }
  
  /* Hover effect on label */
  .container label:hover {
    background-color: #f0f0f0;
  }
  
  /* Style for checked checkbox */
  .container input:checked + label {
    font-weight: bold;
  }
  
  /* Style for price range */
  .container {
    display: flex;
    align-items: center;
  }
  
  /* Style for the text */
  .container label {
    cursor: pointer;
    font-size: 16px;
  }
  
  /* Add some spacing between price range and text */
  .container label::before {
    content: '|';
    margin-right: 10px;
    color: #555;
  }
  @media screen and (max-width: 768px) {
    #filter.show {
      display: block;
    }
  }

</style>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    // Add event listener for the menu icon
    var menuIcon = document.getElementById("menu-icon");
    var filterDiv = document.getElementById("filter");
  
    menuIcon.addEventListener("click", function () {
      // Toggle the 'open' class to display or hide the filter div
      filterDiv.classList.toggle("show");
    });
  });
</script>



{% endblock content %}

templates/oldbooks/edit.html
{% extends "base.html" %}
{% block title %}Edit Profile{% endblock %}
{% block content %}

<style>
    .account-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .account-form input:focus {
        border-color: #1497ff;
        box-shadow: none;
    }
</style>

<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-7  mx-auto">

                        <form class="account-form px-4 pt-4" method="post" enctype="multipart/form-data">

                            {% if form.is_valid %}
                            <div class="alert alert-primary" role="alert">
                                Details successfully updated!
                            </div>
                            <p class="small text-center pt-0">
                                <a href="{% url "account:dashboard" %}">Back to Dashboard</a>
                            </p>
                            {%else%}
                            <h3>Change your details</h3>
                            <p>You can edit your selling books details using the following form:</p>
                            {% endif %}

                            {% if form.errors %}
                            <div class="alert alert-primary" role="alert">
                                Error: Please try again!
                            </div>
                            {% endif %}
                            
                            {% csrf_token %}
                            <div class="form-group pt-5">
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-success"> update </button>
                            </div>
                        </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/oldbooks/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}BookStore{% endblock title %}
{% block content%}
<head>
  <link rel="stylesheet"  href="{% static '/css/product_page2.css' %}">
</head>

<div id = "wrapper">
  <div id="filter">
    <div class="" >
      <!-- Content for the first div -->
    
  
      <div class="box">
        <p><strong>CATEGORIES</strong></p>
    
        {% for c in categoriess %}
        <label class="container{% if categoriess.slug == c.slug %} selected{% endif %}">
          <a class="" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
        </label>
        {% endfor %}
    
      </div>
  </div>
  </div>

      <div class = "products" id = "container">
        {% if products|length == 0 %}

        <h3>  oopsss !!! There are no Products</h3>
        {% endif %}

        {% for product in products %} 
        
        <div class = 'conatiner' style ="cursor: pointer;"   >

          <a href="{{ product.get_absolute_url }}"><img class= 'img-fluid' src="{{ product.image1.url }}" alt="{{ image.image.alt_text }}" ></a>

        <div class = "contentBox">
        
        
        <h4>{{ product.selling_prod.product.title }}</h4>
        <div class = "mixbox">
          
        <p>₹{{ product.discount_price}}</p>
        <p>{{ product.tag }}</p>
          <p class = "strikep">₹{{product.regular_price}}</p>
          <p class = "offerp">({{product.discount_percentage}}% OFF)</p>
              
    
            </div>
            <p>{{ product.selling_user.user.name }}</p>


            </div>
                  
        </div> 
        {% endfor %}  
      </div>  
    
        
        
        
        
        
        
    
      </div>
      <div class="py-4">
        <nav aria-label="Page navigation example">
          {% if products.has_other_pages %}
          <ul class="pagination">
            {% if product.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
            {% endif %}
            {% for num in products.paginator.page_range %}
            {% if products.number == l %}
            <li class="page-item active"><span class="page-link">{{ num }} <span class="sr-only">(current)</span></span>
            </li>
            {% else %}
            <li><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
            {% endfor %}
            {% if products.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">Next</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
            {% endif %}
          </ul>
          {% endif %}
        </nav>
      </div>
</div>

<style>
  .box {
    background-color: #f9f9f9;
    padding: 20px;
    border-radius: 10px;
    margin-bottom: 20px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  }
  
  /* Container styles */
  .container {
    display: block;
    margin-bottom: 10px;
  }
  
  /* Checkbox styles */
  .container input[type="checkbox"] {
    margin-right: 10px;
  }
  
  /* Hover effect on label */
  .container label:hover {
    background-color: #f0f0f0;
  }
  
  /* Style for checked checkbox */
  .container input:checked + label {
    font-weight: bold;
  }
  
  /* Style for price range */
  .container {
    display: flex;
    align-items: center;
  }
  
  /* Style for the text */
  .container label {
    cursor: pointer;
    font-size: 16px;
  }
  
  /* Add some spacing between price range and text */
  .container label::before {
    content: '|';
    margin-right: 10px;
    color: #555;
  }
 
  
  /* Define styles for the 'show' class to display the filter on media view */
  @media screen and (max-width: 768px) {
    #filter.show {
      display: block;
    }
  }
</style>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    // Add event listener for the menu icon
    var menuIcon = document.getElementById("menu-icon");
    var filterDiv = document.getElementById("filter");
  
    menuIcon.addEventListener("click", function () {
      // Toggle the 'open' class to display or hide the filter div
      filterDiv.classList.toggle("show");
    });
  });
</script>

{% endblock content %}

templates/oldbooks/mybooks.html
{% extends 'base.html' %}
{% load static %}
{% block title %}BookStore{% endblock title %}
{% block content%}

{% if messages %}
<div class="alert alert-warning" alert-"{{ message.tags }}" role="alert">
{% for message in messages  %}
{{message|safe}}.
{% endfor %}
</div>
{% endif %}


<div class="position-absolute top-50 start-50 col-12"><h2>My Selling Books</h2></div>

<div id = "wrapper">


      <div class = "products" id = "container">
        
        {% if products|length == 0 %}

        <h3>  oopsss !!! There are no Products</h3>
        {% endif %}

        {% for product in products %} 
        
        <div class = 'conatiner' style ="cursor: pointer;"   >

          <a href="{{ product.get_absolute_url }}"><img class= 'img-fluid' src="{{ product.image1.url }}" alt="{{ image.image.alt_text }}" ></a>

        <div class = "contentBox">
        
        
        <h4>{{ product.selling_prod.product.title }}</h4>

        <div class = "mixbox">
          
        <p>₹{{ product.discount_price}}</p>
        
        <p>{{ product.tag }}</p>
          <p class = "strikep">₹{{product.regular_price}}</p>
          <p class = "offerp">({{product.discount_percentage}}% OFF)</p>
              
    
            </div>
            <p>{{ product.selling_user.user.name }}</p>
            <a type="button" class="btn btn-primary fw500 btn-sm" href="{% url 'sellbook:edit_books' product.id %}">edit</a>
            <a type="button" class="btn btn-danger fw500 btn-sm" href="{% url 'sellbook:delete_books' product.id %}">delete</a>

            </div>
                  
        </div> 
        {% endfor %}  
      </div>  
    
        
        
        
        
        
        
    
      </div>
      <div class="py-4">
        <nav aria-label="Page navigation example">
          {% if products.has_other_pages %}
          <ul class="pagination">
            {% if product.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
            {% endif %}
            {% for num in products.paginator.page_range %}
            {% if products.number == l %}
            <li class="page-item active"><span class="page-link">{{ num }} <span class="sr-only">(current)</span></span>
            </li>
            {% else %}
            <li><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
            {% endfor %}
            {% if products.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">Next</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
            {% endif %}
          </ul>
          {% endif %}
        </nav>
    
</div>



{% endblock content %}

templates/oldbooks/mysoldbooks.html
{% extends 'base.html' %}
{% load static %}
{% block title %}BookStore{% endblock title %}
{% block content%}

{% if messages %}
<div class="alert alert-warning" alert-"{{ message.tags }}" role="alert">
{% for message in messages  %}
{{message|safe}}.
{% endfor %}
</div>
{% endif %}


<div class="position-absolute top-50 start-50 col-12"><h2>My Sold Books</h2></div>

<div id = "wrapper">


      <div class = "products" id = "container">
        
        {% if products|length == 0 %}

        <h3>  oopsss !!! There are no Products</h3>
        {% endif %}

        {% for product in products %} 
        
        <div class = 'conatiner' style ="cursor: pointer;"   >

          <a href="{{ product.get_absolute_url_prod }}"><img class= 'img-fluid' src="{{ product.image1.url }}" alt="{{ image.image.alt_text }}" ></a>

        <div class = "contentBox">
        
        
        <h4>{{ product.selling_prod.product.title }}</h4>

        <div class = "mixbox">
          
        <p>₹{{ product.discount_price}}</p>
        
        <p>{{ product.tag }}</p>
          <p class = "strikep">₹{{product.regular_price}}</p>
          <p class = "offerp">({{product.discount_percentage}}% OFF)</p>
              
    
            </div>
            <p>{{ product.selling_user.user.name }}</p>
            <a type="button" class="btn btn-primary fw500 btn-sm" href="{% url 'sellbook:edit_books' product.id %}">edit</a>
            <a type="button" class="btn btn-danger fw500 btn-sm" href="{% url 'sellbook:delete_books' product.id %}">delete</a>

            </div>
                  
        </div> 
        {% endfor %}  
      </div>  
    
        
        
        
        
        
        
    
      </div>
      <div class="py-4">
        <nav aria-label="Page navigation example">
          {% if products.has_other_pages %}
          <ul class="pagination">
            {% if product.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
            {% endif %}
            {% for num in products.paginator.page_range %}
            {% if products.number == l %}
            <li class="page-item active"><span class="page-link">{{ num }} <span class="sr-only">(current)</span></span>
            </li>
            {% else %}
            <li><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
            {% endfor %}
            {% if products.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">Next</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
            {% endif %}
          </ul>
          {% endif %}
        </nav>
    
</div>


{% endblock content %}

templates/oldbooks/user_orders.html
{% extends "../base.html" %}
{% block title %}Edit Addresses{% endblock %}

{% block content %}
<div class="col-6 mx-auto">
  <h1 class="h3">Create/Edit Address</h1>
  <div>Add a new delivery <b>address</b> and delivery preferences</div>
  <hr />
  <form name="selling_form" class="account-form" method="post" enctype="multipart/form-data">
    {% if form.errors %}
    <div class="alert alert-primary" role="alert">
      Error: Please try again!
    </div>
    {% endif %}
    {{ sell_form.as_p }}
    {% csrf_token %}
    <button class="btn btn-primary btn-block py-2 mb-4 mt-4 fw-bold w-100" type="button" value="Submit" onclick="submitForm()">
    add book 
    </button>
  </form>


</div>

<script> 
function submitForm() {
   var form = document.getElementsByName('selling_form')[0];
   form.submit(); // Submit the form
   form.reset();  // Reset all form data
   return false; // Prevent page refresh
}

</script>

{% endblock %}